name: NeverEnoughMachinery
version: '0.1.0'
main: com.github.darksoulq.nem.NeverEnoughMachinery
api-version: '1.21'
authors: [ DarkSoul ]

dependencies:
  server:
    AbyssalLib:
      required: true
      load: BEFORE
    NeverEnoughRecipes:
      required: true
      load: BEFORE
    Minetorio:
      required: true
      load: BEFORE